### ISSUE TITLE
How to set stmin when use transfer_data()

### ISSUE THREAD

**Issue by trandangkhoadev** [pylessard/python-can-isotp#101]
I'm using Transport layer and PythonIsoTpConnection but when I call transfer_data() the stmin will respect the stmin requirement of receiver. 
In case stmin from receiver as 0. The transfer_data() will send the cantp frame to fast such as stmin= 0.2ms. So how can I increase the delay between 2 frames in this case.

**Comment by pylessard** [comment]
Can you explain why it is too fast?  
 - Is it because the receiver can not take it?  In that case, the receiver should not set stmin = 0
 - Is it because you overflow the transmit queue? In that case look at the [rate limiter
](https://can-isotp.readthedocs.io/en/v1.x/isotp/implementation.html#rate-limiter)
You are quite lucky, because I happen to have added a parameter to override the receiver stmin tonight.  This is still under developement and will be part of the unreleased isotp v2.x.  The parameter will be `override_receiver_stmin`

https://github.com/pylessard/python-can-isotp/compare/v2.x...document_new_params#diff-1e3ed06e90fe3bf5ecf311ac1bd22215144cfc8c0924f5e05e3394573d630cebR32

**Comment by pylessard** [comment]
Moving this issue to python-can-isotp module

**Comment by trandangkhoadev** [comment]
When I use ver 2.x and set stmin = 0.001 but the actual stmin is 16ms. So how can I have the stmin 0.5 ms ? Because my hardware only work with stmin = 0.5ms

**Comment by pylessard** [comment]
That's progress!
I'm actively working into improving timings.  It's hard to do in a fully portable fashion in pure-python.
Can you try to move you udsoncan repo to the `support-isotp-v2` branch?    Hopefully, you will get better timings.

Note that I still have some work to do, like enabling the use of the CAN notifier which seems to provide betterperformance as pointed out in this issue: https://github.com/pylessard/python-udsoncan/issues/169

**Comment by trandangkhoadev** [comment]
So that means, if we only set override_receiver_stmin to 0, it actually results in a delay of 0.2ms, and if we set override_receiver_stmin to 0.0001, it actually causes a delay of 16ms. Is there no other way to achieve a delay in the range of 0.5ms to 16ms?

**Comment by pylessard** [comment]
Yes an no.
On Windows, the thread resolution is 16ms, but its finer on Linux. So that is OS dependent.
I believe windows 11 offer some high resolution timer, which could allow busy-waiting. I plan into looking into it soon for v2.x

On Linux, you will have better timing for sure. If you use Linux, you can also look into the kernel module that offer IsoTP under the socket API. 

Di you get better result with the udsoncan branch I suggested?

**Comment by pylessard** [comment]
following up on this?
I may close this issue if no answer. cheers
