### ISSUE TITLE
Preformance issue of func "specific_wait_frame"

### ISSUE THREAD

**Issue by XXIN0** [pylessard/python-can-isotp#125]
Hi pylessard,

**softversion**
can-isotp:  2.0.4
computer: win10
python:  3.8.10 32bit

When I  send a uds(service 36) packet complete, it always  wait 20ms-30ms for the program to send the next packet of data. Through testing I found the func `specific_wait_frame` always wait  some time, how to minimize the `specific_wait_frame`  wait time?

![image](https://github.com/pylessard/python-can-isotp/assets/41498132/35c9eec8-8a58-4f57-8dfb-5c601d0fdfb9)
![image](https://github.com/pylessard/python-can-isotp/assets/41498132/fb920e61-b48c-4acd-b02c-ec31fd36e46a)
![image](https://github.com/pylessard/python-can-isotp/assets/41498132/0d076a08-b9d6-4d86-a92f-9b6c8d4d29c7)

**Comment by pylessard** [comment]
Hi,
What connection do you use?
Can you share the python logging output with debug logging enabled?

Windows has a thread resolution of 16ms, so you certainly have 2 time slices of wait time.  It really depends on your setup and the underlying library.   Possible that the underlying library is wasting a time slice before passing the data up.

**Comment by XXIN0** [comment]
HI,
Hardware：vector VN5640

log info:
check the attachment file for the tp log.
[tp_log.txt](https://github.com/pylessard/python-can-isotp/files/15426651/tp_log.txt)
![image](https://github.com/pylessard/python-can-isotp/assets/41498132/c5f92937-d7d2-4fa4-8a69-6a2ee1095d71)

**Comment by XXIN0** [comment]
I found that I can configure this sleep  timing through the function `set_sleep_timing` to reduce the wait time.

**Comment by pylessard** [comment]
You have not shared the connection you used. And I don't see the the startup in the logs.
set_sleep_timing is deprecated and is not supposed to have an effect.

With v2.x, your rxfn is supposed to be blocking and you should call "start" on isotp stack. Check : https://can-isotp.readthedocs.io/en/latest/#v2-x-changes

if changing the sleep_timing has an effect, the code is trying to cope with backward compatibility, probably here : 
https://github.com/pylessard/python-can-isotp/blob/v2.x/isotp/protocol.py#L1609

If your rxfn has a timeout parameter and that parameter is used to do a blocking read, this should not happen. Performance will be much better with blocking read. 

If you show how you setup your stack, I can point where the issue is.

**Comment by XXIN0** [comment]
I'm using   `PythonIsoTpConnection` in  `udsoncan.connections ` to connect  the `isotp`.
![image](https://github.com/pylessard/python-can-isotp/assets/41498132/751d006f-0efc-4d73-a333-eac8358c0622)

start up log.
![image](https://github.com/pylessard/python-can-isotp/assets/41498132/9e0d0d0a-e6c4-46b6-9106-3424bb2af76c)

It seems that the code here has done blocking processing.
![image](https://github.com/pylessard/python-can-isotp/assets/41498132/67797225-4931-40a0-8bc1-c284e49e5c1f)

**Comment by XXIN0** [comment]
I upgraded the new udsoncan library and your implementation was updated,this problem is solved.

**Comment by pylessard** [comment]
Ah, yes. v1.21+ is required to take advantage of the timing improvements introduced in isotp v2.
What version were you using?

regards

**Comment by XXIN0** [comment]
> Ah, yes. v1.21+ is required to take advantage of the timing improvements introduced in isotp v2. What version were you using?
> 
> regards

v1.13.1, hhh, It's a lot of versions behind the new version
