### ISSUE TITLE
Replacing the bytearray data handling with Generator

### ISSUE THREAD

**Issue by geynis** [pylessard/python-can-isotp#90]
As CAN-FD supports up to 4GB of data, the code should not convert the data to bytearray. Instead the data should be handled as an iterator of bytes to let the user use a byte generator.

**Comment by pylessard** [comment]
CAN-FD supports frames up to 64 bytes.
You probably are referring to the ISO-TP frame size as defined since the 2016 version where data length is 32 bits (instead of 12 bits as before).

I understand the request. Do you have a real use-case for it? 
IF this gets implemented, it would need to be a pair of generator and max length since the payload size needs to be known at the beginning of the transmission

**Comment by geynis** [comment]
Hi, yes, I'm referring to the max ISO-TP length for CAN-FD.
Yes it can be a a pair with max length or it can be a single object that
implements __len__ .

**Comment by geynis** [comment]
BTW, if you just remove any casting to bytearray the user could provide a
costume object that will generate the data on the fly.

**Comment by pylessard** [comment]
Can I know what kind of use case requires that?

**Comment by geynis** [comment]
Cyber Security Testing

**Comment by pylessard** [comment]
Ok, this will go in the todo list.   You can propose a PR (with unit test) if you want.

**Comment by geynis** [comment]
Yes, Thanks!

**Comment by pylessard** [comment]
Will be available in v2.x

**Comment by geynis** [comment]
hi @pylessard , thanks for the implementation. I don't think you need to implement it as a tuple, generators can return length with the _len_ function. e.g. _range_ is a generator and has a length without generating all the elements.

**Comment by pylessard** [comment]
Hi @geynis , I know generators can have a length, but they are not required to. So either I ask the user to provide a custom generator that implements the __len__ function or I ask for the length explicitely.  I find the API for a tuple more simple, even if it requires few additional characters (a comma and paranthesis). 

In my experience, an explicit API avoid confusion and weird bugs. If a user implements the __len__ function, the user may think that it should return the remaining number of element instead of the total, which would be an issue. It's just a dumb example.

Cheers
